name: package

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
         node-version: '24'
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive-tools aria2

      - name: Remove old symlinks
        run: |
          rm -rf blockbench*latest.deb

      - name: Build armhf
        run: |
          rm -rf ./blockbench*/
          export version=$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          git clone https://github.com/JannisX11/blockbench.git
          cd blockbench && npm install
          npm run build-electron
          npx electron-builder --linux --armv7l --publish never
      - name: Build arm64
        run: |
          rm -rf ./blockbench*/
          export version=$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          git clone https://github.com/JannisX11/blockbench.git
          cd blockbench && npm install 
          npm run build-electron
          npx electron-builder --linux --arm64 --publish never
      - name: Create symlinks
        run: |
          export version=$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          rm -rf ./*latest.deb
          ln -fs "$(find . -name '*arm64.deb' -type f -printf '%P\n' -quit)" blockbench-arm64-latest.deb
          ln -fs "$(find . -name '*armhf.deb' -type f -printf '%P\n' -quit)" blockbench-armhf-latest.deb

      - name: Upload
        run: |
          rm -rf ./blockbench*/
          export version=$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          echo $version > current.txt
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload blockbench v$(curl -s https://api.github.com/repos/JannisX11/blockbench/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
